baseURL = "https://tomdpb.github.io/toms-territory/"
languageCode = 'en-gb'
title = "Tom's Territory"
theme = 'PaperMod'
defaultContentLanguage = 'en'
enableRobotsTXT = false
ShowToc = true
ShowCodeCopyButtons = true
