[de]
  languageName = 'Deutsch'
  languageCode = "de"
  languageDirection = "ltr"
  weight = 1
  title = 'Toms Territorium'
  [de.params]
    homeinfoparams.title = "Kontakt"
  [de.permalinks]
    projects = "/projekte/:slug"

[en]
  languageName = 'English (UK)'
  languageCode = "en-GB"
  languageDirection = "ltr"
  weight = 2
  title = "Tom's Territory"
  [en.params]
    homeinfoparams.title = "Contact"
  [en.permalinks]
    projects = "/projects/:slug"

[es]
  languageName = "Español"
  languageCode = "es"
  languageDirection = "ltr"
  weight = 3
  title = "Territorio de Tom"
  [es.params]
    homeinfoparams.title = "Contacto"
  [es.permalinks]
    projects = "/proyectos/:slug"

[it]
  languageName = "Italiano"
  languageCode = "it"
  languageDirection = "ltr"
  weight = 4
  title = "Territorio di Tom"
  [it.params]
    homeinfoparams.title = "Contatto"
  [it.permalinks]
    projects = "/progetti/:slug"

[pt]
  languageName = 'Português (BR)'
  languageCode = "pt-br"
  languageDirection = "ltr"
  weight = 5
  title = "Território do Tom"
  [pt.params]
    homeinfoparams.title = "Contato"
  [pt.permalinks]
    projects = "/projetos/:slug"
