[[main]]
  identifier = "about_me"
  name = "Über mich"
  url = "/about/about_me"
  weight = 1

[[main]]
  identifier = "blog"
  name = "Blog"
  pageRef = "/blog/"
  weight = 2

[[main]]
  identifier = "projects"
  name = "Projekte"
  pageRef = "/projects/"
  weight = 3
