[[main]]
  identifier = "about_me"
  name = "Sobre mí"
  pageRef = "/about/about_me.es.md"
  weight = 1

[[main]]
  identifier = "blog"
  name = "Blog"
  pageRef = "/blog"
  weight = 2

[[main]]
  identifier = "projects"
  name = "Proyectos"
  pageRef = "/projects"
  weight = 3
