defaultTheme = "auto"
disableThemeToggle = false
showToc = true

[homeInfoMode]
enabled = true


[[socialIcons]]
name = "email"
url = "mailto:plutomega@proton.me"

[[socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/thomas-de-paula-barbosa-17302b243"

[[socialIcons]]
name = "GitHub"
url = "https://github.com/tomdpb"

[[socialIcons]]
name = "Gitlab"
url = "https://gitlab.com/tomdpb"

[[socialIcons]]
name = "Kofi"
url = "https://ko-fi.com/tomdpb"

