[[main]]
  identifier = "about_me"
  name = "Über mich"
  url = "about/"
  weight = 1

[[main]]
  # somehow, only blog works. Maybe this is because it is untranslateable?
  identifier = "blog"
  name = "Blog"
  url = "blog/"
  weight = 2

[[main]]
  identifier = "projects"
  name = "Projekte"
  url = "projects/"
  weight = 3
