[[main]]
  name = "About me"
  pageRef = "/about/about_me.en.md"
  weight = 1

[[main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 2

[[main]]
  name = "Projects"
  pageRef = "/projects"
  weight = 3
