[[main]]
  name = "Su di me"
  pageRef = "/about/about_me.it.md"
  weight = 1

# [[main]]
#   name = "Blog"
#   pageRef = "/blog"
#   weight = 2

[[main]]
  name = "Progetti"
  pageRef = "/projects"
  weight = 3
